default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: linked_in_parser_development

test:
  <<: *default

production:
  <<: *default
